### PR TITLE
Fix assertion rendering on mock failures

### LINKED ISSUE #35: UnsatisfiedExpectationsException: null
When running mocks with ZIO 2.0.2 and zio-mock 1.0.0-RC9, I get the following exception:
```
Exception in thread "zio-fiber-49" zio.mock.internal.MockException$UnsatisfiedExpectationsException: null
    	at zio.mock.internal.MockState$.$anonfun$checkUnmetExpectations$3(MockState.scala:41)
```

To reproduce:
```scala
import zio._
import zio.mock.{Expectation, Mock}
import zio.stream.ZStream
import zio.test._
import zio.test.Assertion._

object reproduce extends ZIOSpecDefault {
  trait Foo {
    def createDocument(document: ZStream[Any, Throwable, Byte]): Task[Unit]
  }

  object FooMock extends Mock[Foo] {
    object CreateDocument extends Effect[ZStream[Any, Throwable, Byte], Throwable, Unit]

    val compose: URLayer[mock.Proxy, Foo] = ZLayer.fromFunction { (proxy: mock.Proxy) =>
      new Foo {
        override def createDocument(document: ZStream[Any, Throwable, Byte]): Task[Unit] =
          proxy(CreateDocument, document)
      }
    }
  }

  def spec = suite("mocks")(
    test("fail?") {
      for {
        _ <- ZIO.serviceWithZIO[Foo](_.createDocument(ZStream.empty))
      } yield assertCompletes
    }.provide(
      FooMock.CreateDocument(equalTo(ZStream.empty), Expectation.unit)
    )
  )
}
```
Scastie: https://scastie.scala-lang.org/soujiro32167/p6PBZRuGQwa7vXrmToKt8w/7

### PR DESCRIPTION
**Pull request by SirStoke**
Fixes #35 by using the utilities implemented in zio/zio#7641

### CODE REVIEW

**Comment by SirStoke** [comment]
I see the `#render()` method on assertions was rolled back in zio/zio#7713, I'm going to convert this to draft until a new one gets implemented

**Comment by regiskuckaertz** [comment]
@SirStoke hello 👋 do you have capacity to rebase your PR? very interested in that lovely fix 😄

**Comment by regiskuckaertz** [comment]
Hmm, actually the `render` method has been reverted due to some other issues, we need to give it a bit more thought

**Comment by mikail-khan** [comment]
Any news on when this PR can be updated and merged?

**Comment by leszekgruchala** [comment]
@mikail-khan It's not ideal, but you can extend your spec with `MockSpecDefault` to render the mock failures information.

**Comment by jgranstrom** [comment]
Is this back on the table now with https://github.com/zio/zio/pull/8498?

**Comment by SirStoke** [comment]
> Is this back on the table now with [zio/zio#8498](https://github.com/zio/zio/pull/8498)?

Hi! It seems like it would be, but I'm not involved with zio at work anymore, so I don't really have the motivation or time to fix the PR. Sorry about that.

FWIW, unless something major has changed in zio-mock, it should be really easy to port this fix using the new method

**Pull request closed without merging**
